[Admin] - obsługa błędów API w formularzach - 42
typeofweb/sklep pull request #171
Opened 2020-11-09 17:14 UTC by jundymek

W przypadku ominięcia zabezpieczeń na froncie, przychodzi błąd z serwera i na jego podstawie ustawiany jest błąd w odniesieniu do konkretnego pola `final-form`.

2020-11-09 18:21 UTC, wisnie commented on apps/www/components/admin/orderForm/OrderForm.tsx
>        } catch (err) {
Nie musisz używać `return` blok `catch` wywoła się tylko w przypadku błędu w bloku `try`

2020-11-09 18:23 UTC, mmiszy requested changes

2020-11-09 18:23 UTC, mmiszy commented on apps/www/components/admin/productsForm/ProductsForm.tsx
> +}
Zduplikowane typy

2020-11-09 18:23 UTC, mmiszy commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +  readonly validation: Validation;
Pushnąłem Ci do brancha zmiany, które dodają więcej informacji do tego błędu. Przykładowo, teraz będzie wyglądał tak:

```ts
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "string.base. any.required",
  "validation": {
    "source": "payload",
    "keys": ["name", "description", "regularPrice"]
  },
  "details": [
    {
      "message": "string.base",
      "path": ["name"],
      "type": "string.base"
    },
    {
      "message": "string.base",
      "path": ["description"],
      "type": "string.base"
    },
    {
      "message": "any.required",
      "path": ["regularPrice"],
      "type": "any.required"
    }
  ]
}
```

Powinniśmy skorzystać z pola `details`: pole to będzie `details[…].path`, a błąd wyświetlić na podstawie `details[…].type`. Celowo usunąłem angielskie komunikaty błędów, żebyśmy mogli na froncie to lepiej obsłużyć, coś w stylu:

```ts
const badRequestErrorsTranslation = {
  'any.required': 'To pole jest wymagane',
  'string.base': 'Pole musi być tekstem',
};
```

2020-11-09 18:26 UTC, mmiszy commented on apps/www/components/admin/orderForm/OrderForm.tsx
> +        return await mutate(body);
```suggestion
        await mutate(body);
```
Ta funkcja nie może nic zwracać jeśli nie było błędu.

2020-11-12 22:47 UTC, jundymek commented on apps/www/components/admin/orderForm/OrderForm.tsx
>        } catch (err) {
poprawione

2020-11-12 22:47 UTC, jundymek commented on apps/www/components/admin/productsForm/ProductsForm.tsx
> +}
usunięte

2020-11-12 22:47 UTC, jundymek commented on apps/www/components/admin/orderForm/OrderForm.tsx
> +        return await mutate(body);
oki

2020-11-12 22:48 UTC, jundymek commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +  readonly validation: Validation;
zrobione. Mam nadzieję, że o to chodziło.

2020-11-13 02:33 UTC, mmiszy requested changes

2020-11-13 02:33 UTC, mmiszy commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +        return { [`${error.path[0]}`]: getTranslatedErrorMessage('error.message') };
```suggestion
        return { [error.path[0]]: getTranslatedErrorMessage(error.message) };
```

2020-11-13 02:33 UTC, mmiszy commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +      .reduce((error1, error2) => Object.assign(error1, error2), {});
Super!

2020-11-13 02:33 UTC, mmiszy commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +    : 'Popraw pole';
Dodałbym tutaj console.warn() jeśli danego message nie było w naszym obiekcie badRequestErrorsTranslation

2020-11-13 02:33 UTC, mmiszy commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +  return err;
```suggestion
  throw err;
```

2020-11-13 02:35 UTC, mmiszy commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +export function serverErrorHandler(err: unknown) {
Fajnie by było dopisać jakieś testy jednostkowe do tej funkcji :)

2020-11-15 10:00 UTC, jundymek commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +        return { [`${error.path[0]}`]: getTranslatedErrorMessage('error.message') };
Ups... Poprawione.

2020-11-15 10:01 UTC, jundymek commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +      .reduce((error1, error2) => Object.assign(error1, error2), {});
:)

2020-11-15 10:04 UTC, jundymek commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +    : 'Popraw pole';
Dodane

2020-11-15 10:04 UTC, jundymek commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +  return err;
ok

2020-11-16 01:53 UTC, jundymek commented on apps/www/components/admin/productsForm/utils/serverErrorHandler.ts
> +export function serverErrorHandler(err: unknown) {
Dopisałem kilka testów.

2020-11-17 15:37 UTC, mmiszy approved these changes

2020-11-18 13:53 UTC, merged