81 image upload api
typeofweb/sklep pull request #174
Opened 2020-11-21 18:13 UTC by wisnie

2020-11-21 20:51 UTC, kosmalaa commented on apps/api/src/plugins/media/mediaFunctions.ts
> +  readonly productId?: number | null;
Potrzebny tutaj jest ten null jak parametr jest opcjonalny?

2020-11-21 21:29 UTC, wisnie commented on apps/api/src/plugins/media/mediaFunctions.ts
> +  readonly productId?: number | null;
Prisma generuje typy opcjonalne z bazy danych jako `typ | null | undefined`

2020-11-25 07:12 UTC, wilkadrian commented on apps/api/src/plugins/media/index.ts
> +        await Promise.allSettled([
Tutaj chyba lepiej użyć Promise.all, w razie czego walnie błędem.

2020-11-25 19:10 UTC, wisnie commented on apps/api/src/plugins/media/index.ts
> +        await Promise.allSettled([
Na początku mieliśmy tutaj `Promise.all`, lecz potem stwierdziliśmy, że `Promise.allSettled`, żeby móc dokładnie ustalić co się stanie, w wypadku błędu jednej z operacji. Narazie to nie jest zaimplementowane, ale raczej zrobimy tak, że zawsze się usuwa z bazy nawet jeśli się nie uda usunąć z dysku.

2020-11-28 22:47 UTC, wilkadrian requested changes
Jest super, testy by się przydały jeszcze :D

2020-11-28 22:47 UTC, wilkadrian commented on apps/api/src/plugins/media/index.ts
> +          await fs.promises.unlink(filePathWithExtension);
```suggestion
          await deleteImage(filePathWithExtension);
```

2020-11-28 22:47 UTC, wilkadrian commented on apps/types/package.json
> +    "generate-api-types": "wait-on tcp:3002 --interval 5000 && yarn swagger-to-ts http://api.sklep.localhost:3002/swagger.json --output types.ts --prettier-config ../../.prettierrc --fileType \"{read
Ta końcówka linijki to do czego?

2020-11-30 15:20 UTC, wisnie commented on apps/api/src/plugins/media/index.ts
> +          await fs.promises.unlink(filePathWithExtension);
Tak masz rację, można to wydzielić, pomyślałem, że jedną linijkę można zostawić, ale chyba będzie bardziej clean jak wydzielimy.

2020-11-30 15:23 UTC, wisnie commented on apps/types/package.json
> +    "generate-api-types": "wait-on tcp:3002 --interval 5000 && yarn swagger-to-ts http://api.sklep.localhost:3002/swagger.json --output types.ts --prettier-config ../../.prettierrc --fileType \"{read
Ta końcówka jest do poprawnego wygenerowania typu w Hapi.js. Generalnie to działa tak, że mamy w api plugin Swaggera, który korzysta ze Scheme napisanych w Joi i następnie na podstawie tego Swaggera i biblioteki Swagger-to-ts  generujemy typy, które potem są za pomocą różnych przekształceń eksportowane jako paczka @SklepTypes. Niestety używając biblioteki Joi  nie możemy zrobić `Joi.file` i musimy użyć takiego obejścia. Tak w skrócie.

2021-05-25 16:23 UTC, mmiszy approved these changes

2021-05-25 16:51 UTC, merged